# Generated by Django 5.2.5 on 2025-09-23 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or URL for the service', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Institute Service',
                'verbose_name_plural': 'Institute Services',
                'db_table': 'institute_services',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='institute_s_name_35e14e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Institute logo image', null=True, upload_to='institutes/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute_services', models.ManyToManyField(blank=True, help_text='Services offered by this institute', related_name='institutes', to='core.instituteservice')),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
                'db_table': 'institutes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstituteModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('group', models.ForeignKey(help_text='Django auth group for this module', on_delete=django.db.models.deletion.CASCADE, related_name='institute_modules', to='auth.group')),
                ('institute', models.ForeignKey(help_text='The institute this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.institute')),
                ('users', models.ManyToManyField(blank=True, help_text='Users assigned to this institute module', related_name='institute_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institute Module',
                'verbose_name_plural': 'Institute Modules',
                'db_table': 'institute_modules',
                'ordering': ['institute__name', 'group__name'],
                'indexes': [models.Index(fields=['institute'], name='institute_m_institu_73e564_idx'), models.Index(fields=['group'], name='institute_m_group_i_524c47_idx')],
                'unique_together': {('institute', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['name'], name='institutes_name_1815c2_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['phone'], name='institutes_phone_f185dd_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['latitude', 'longitude'], name='institutes_latitud_9c3f08_idx'),
        ),
    ]
