# Generated by Django 5.2.5 on 2025-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instituteservice_institute_institutemodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mypay_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'My Setting',
                'verbose_name_plural': 'My Settings',
                'db_table': 'my_settings',
            },
        ),
    ]
