# Generated by Django 5.2.5 on 2025-10-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_token',
            field=models.CharField(blank=True, db_column='biometric_token', max_length=500, null=True),
        ),
    ]
