# Generated by Django 5.2.5 on 2025-10-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wallet_user_users_biometr_c9b074_idx_wallet_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
