# Generated by Django 5.2.5 on 2025-10-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='institutemodule',
            options={'ordering': ['institute__name', 'module__name'], 'verbose_name': 'Institute Module', 'verbose_name_plural': 'Institute Modules'},
        ),
        migrations.RemoveIndex(
            model_name='institutemodule',
            name='institute_m_group_i_524c47_idx',
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['name'], name='modules_name_0c405d_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['slug'], name='modules_slug_7b8e4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutemodule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='institutemodule',
            name='module',
            field=models.ForeignKey(help_text='Module for this institute module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_modules', to='core.module'),
        ),
        migrations.AlterUniqueTogether(
            name='institutemodule',
            unique_together={('institute', 'module')},
        ),
        migrations.AddIndex(
            model_name='institutemodule',
            index=models.Index(fields=['module'], name='institute_m_module__8b82ff_idx'),
        ),
        migrations.RemoveField(
            model_name='institutemodule',
            name='group',
        ),
    ]
