# Generated by Django 5.2.5 on 2025-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_module_alter_institutemodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=13, null=True),
        ),
    ]
