# Generated by Django 5.2.5 on 2025-11-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_user_is_active_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_active_idx',
        ),
    ]
