# Generated by Django 5.2.5 on 2025-11-18 00:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_users_is_active_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodule',
            name='expire_date',
            field=models.DateTimeField(blank=True, db_column='expire_date', help_text='Expiration date for this institute module', null=True),
        ),
        migrations.AddField(
            model_name='institutemodule',
            name='renewal_price',
            field=models.DecimalField(blank=True, db_column='renewal_price', decimal_places=2, help_text='Renewal price for this institute module', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='call_price',
            field=models.DecimalField(db_column='call_price', decimal_places=2, default=Decimal('0.00'), help_text='Default call price', max_digits=15),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='parent_price',
            field=models.DecimalField(db_column='parent_price', decimal_places=2, default=Decimal('0.00'), help_text='Default parent price', max_digits=15),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='sms_price',
            field=models.DecimalField(db_column='sms_price', decimal_places=2, default=Decimal('0.00'), help_text='Default SMS price', max_digits=15),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='vat_percent',
            field=models.DecimalField(db_column='vat_percent', decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage', max_digits=5),
        ),
    ]
