# Generated by Django 5.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


def set_default_sms_character_price(apps, schema_editor):
    """Set default sms_character_price value for existing MySetting records"""
    MySetting = apps.get_model('core', 'MySetting')
    MySetting.objects.all().update(sms_character_price=160)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='sms_character_price',
            field=models.IntegerField(db_column='sms_character_price', default=160, help_text='Number of characters per SMS part (default: 160)'),
        ),
        migrations.RunPython(set_default_sms_character_price, migrations.RunPython.noop),
    ]
