# Generated by Django 5.2.5 on 2025-12-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        ('device', '0013_devicecart_devicecartitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySirenBuzzer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('delay', models.IntegerField(help_text='Delay in seconds before buzzer activation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('device', models.ForeignKey(help_text='Device associated with this buzzer', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_buzzers', to='device.device')),
                ('institute', models.ForeignKey(help_text='Institute this buzzer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_buzzers', to='core.institute')),
            ],
            options={
                'verbose_name': 'Community Siren Buzzer',
                'verbose_name_plural': 'Community Siren Buzzers',
                'db_table': 'community_siren_buzzers',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='community_s_title_82cad2_idx'), models.Index(fields=['institute'], name='community_s_institu_efeda9_idx'), models.Index(fields=['device'], name='community_s_device__7c09df_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunitySirenContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('is_sms', models.BooleanField(default=True, help_text='Send SMS notifications')),
                ('is_call', models.BooleanField(default=False, help_text='Make phone calls')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_contacts', to='core.institute')),
            ],
            options={
                'verbose_name': 'Community Siren Contact',
                'verbose_name_plural': 'Community Siren Contacts',
                'db_table': 'community_siren_contacts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='community_s_name_0b2a9e_idx'), models.Index(fields=['phone'], name='community_s_phone_0d15f0_idx'), models.Index(fields=['institute'], name='community_s_institu_c67716_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunitySirenHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('app', 'App'), ('geofence', 'Geofence'), ('switch', 'Switch')], help_text='Source of the alert (app or switch)', max_length=20)),
                ('name', models.CharField(help_text='Name of the person/entity', max_length=255)),
                ('primary_phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=13, null=True)),
                ('datetime', models.DateTimeField(help_text='Date and time of the alert')),
                ('images', models.ImageField(blank=True, help_text='Alert images', null=True, upload_to='community_siren_history/')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the alert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this alert belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_histories', to='core.institute')),
            ],
            options={
                'verbose_name': 'Community Siren History',
                'verbose_name_plural': 'Community Siren Histories',
                'db_table': 'community_siren_histories',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['source'], name='community_s_source_65b2ef_idx'), models.Index(fields=['status'], name='community_s_status_a779dc_idx'), models.Index(fields=['institute'], name='community_s_institu_ab501b_idx'), models.Index(fields=['datetime'], name='community_s_datetim_60bc9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunitySirenMembers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(help_text='User who is a member of community siren', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Siren Member',
                'verbose_name_plural': 'Community Siren Members',
                'db_table': 'community_siren_members',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='community_s_user_id_390fbe_idx')],
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='CommunitySirenSwitch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=13)),
                ('trigger', models.IntegerField(help_text='Trigger radius in meters')),
                ('primary_phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, help_text='Switch image', null=True, upload_to='community_siren_switches/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('device', models.ForeignKey(help_text='Device associated with this switch', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_switches', to='device.device')),
                ('institute', models.ForeignKey(help_text='Institute this switch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_switches', to='core.institute')),
            ],
            options={
                'verbose_name': 'Community Siren Switch',
                'verbose_name_plural': 'Community Siren Switches',
                'db_table': 'community_siren_switches',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='community_s_title_da2cca_idx'), models.Index(fields=['institute'], name='community_s_institu_4d6c4c_idx'), models.Index(fields=['device'], name='community_s_device__e1a9b3_idx'), models.Index(fields=['latitude', 'longitude'], name='community_s_latitud_34132f_idx')],
            },
        ),
    ]
