# Generated by Django 5.2.5 on 2025-12-13 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_siren', '0001_initial'),
        ('core', '0012_institutemodule_expire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysirenhistory',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Member (user) who clicked the SOS button', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_siren_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communitysirenhistory',
            index=models.Index(fields=['member'], name='community_s_member__2dcb16_idx'),
        ),
    ]
