# Generated by Django 5.2.5 on 2025-12-20 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_siren', '0002_communitysirenhistory_member_and_more'),
        ('core', '0012_institutemodule_expire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitysirenmembers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='communitysirenmembers',
            name='institute',
            field=models.ForeignKey(default=25, help_text='Institute this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='community_siren_members', to='core.institute'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='communitysirenmembers',
            unique_together={('user', 'institute')},
        ),
        migrations.AddIndex(
            model_name='communitysirenmembers',
            index=models.Index(fields=['institute'], name='community_s_institu_bef18e_idx'),
        ),
    ]
