# Generated by Django 5.2.5 on 2025-12-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Description of the public vehicle', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Whether the vehicle is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this public vehicle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='public_vehicles', to='core.institute')),
            ],
            options={
                'verbose_name': 'Public Vehicle',
                'verbose_name_plural': 'Public Vehicles',
                'db_table': 'public_vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicVehicleImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Vehicle image', upload_to='public_vehicles/images/')),
                ('order', models.IntegerField(default=0, help_text='Order of the image for display')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('public_vehicle', models.ForeignKey(help_text='Public vehicle this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public_vehicle.publicvehicle')),
            ],
            options={
                'verbose_name': 'Public Vehicle Image',
                'verbose_name_plural': 'Public Vehicle Images',
                'db_table': 'public_vehicle_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicvehicle',
            index=models.Index(fields=['institute'], name='public_vehi_institu_aea1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='publicvehicle',
            index=models.Index(fields=['is_active'], name='public_vehi_is_acti_86667b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicvehicle',
            index=models.Index(fields=['created_at'], name='public_vehi_created_87a404_idx'),
        ),
        migrations.AddIndex(
            model_name='publicvehicleimage',
            index=models.Index(fields=['public_vehicle'], name='public_vehi_public__bb2d51_idx'),
        ),
        migrations.AddIndex(
            model_name='publicvehicleimage',
            index=models.Index(fields=['order'], name='public_vehi_order_0cf83a_idx'),
        ),
    ]
