# Generated by Django 5.2.5 on 2025-12-02 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        ('fleet', '0008_vehicle_number_plate_photo_and_more'),
        ('public_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicvehicle',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle assigned as public vehicle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_vehicles', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='publicvehicleimage',
            name='title',
            field=models.CharField(blank=True, help_text='Title for the image', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='publicvehicle',
            unique_together={('institute', 'vehicle')},
        ),
        migrations.AddIndex(
            model_name='publicvehicle',
            index=models.Index(fields=['vehicle'], name='public_vehi_vehicle_6f4fec_idx'),
        ),
    ]
