# Generated by Django 5.2.5 on 2025-12-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_number_plate_photo_and_more'),
        ('public_vehicle', '0002_publicvehicle_vehicle_publicvehicleimage_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVehicleSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, help_text="User's location latitude for proximity notifications", max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, help_text="User's location longitude for proximity notifications", max_digits=19)),
                ('notification', models.BooleanField(default=True, help_text='Whether notifications are enabled for this subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(help_text='User who subscribed to the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='public_vehicle_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Public vehicle being subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='public_vehicle_subscriptions', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Public Vehicle Subscription',
                'verbose_name_plural': 'Public Vehicle Subscriptions',
                'db_table': 'public_vehicle_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='public_vehi_user_id_7a108a_idx'), models.Index(fields=['vehicle'], name='public_vehi_vehicle_d517e5_idx'), models.Index(fields=['user', 'vehicle'], name='public_vehi_user_id_d26898_idx'), models.Index(fields=['notification'], name='public_vehi_notific_851990_idx')],
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
