# Generated by Django 5.2.5 on 2025-10-13 04:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Wallet creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Last wallet update timestamp')),
                ('user', models.OneToOneField(db_column='user_id', help_text='User who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Type of transaction', max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after transaction', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Description or reason for transaction', null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Unique reference for this transaction', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', help_text='Transaction status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Transaction creation timestamp')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Admin user who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet'], name='transaction_wallet__c63ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['performed_by'], name='transaction_perform_248e6d_idx'),
        ),
    ]
