# Generated by Django 5.2.5 on 2025-11-18 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='call_price',
            field=models.DecimalField(blank=True, db_column='call_price', decimal_places=2, help_text='Call price for this wallet', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='sms_price',
            field=models.DecimalField(blank=True, db_column='sms_price', decimal_places=2, help_text='SMS price for this wallet', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='DueTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, help_text='Subtotal amount before VAT', max_digits=15)),
                ('vat', models.DecimalField(db_column='vat', decimal_places=2, help_text='VAT amount', max_digits=15)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, help_text='Total amount including VAT', max_digits=15)),
                ('renew_date', models.DateTimeField(db_column='renew_date', help_text='Renewal date for this transaction')),
                ('expire_date', models.DateTimeField(db_column='expire_date', help_text='Expiration date for this transaction')),
                ('is_paid', models.BooleanField(db_column='is_paid', default=False, help_text='Whether this due has been paid')),
                ('pay_date', models.DateTimeField(blank=True, db_column='pay_date', help_text='Date when payment was made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Transaction creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Last update timestamp')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User who owes this due', on_delete=django.db.models.deletion.CASCADE, related_name='due_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Due Transaction',
                'verbose_name_plural': 'Due Transactions',
                'db_table': 'due_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DueTransactionParticular',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('particular', models.TextField(db_column='particular', help_text='Description of this particular item')),
                ('type', models.CharField(choices=[('vehicle', 'Vehicle'), ('parent', 'Parent')], db_column='type', help_text='Type of particular (vehicle or parent)', max_length=20)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, help_text='Unit amount for this particular', max_digits=15)),
                ('quantity', models.IntegerField(db_column='quantity', default=1, help_text='Quantity of this particular')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, help_text='Total amount (amount * quantity)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Particular creation timestamp')),
                ('due_transaction', models.ForeignKey(db_column='due_transaction_id', help_text='The due transaction this particular belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='finance.duetransaction')),
                ('institute', models.ForeignKey(blank=True, db_column='institute_id', help_text='Institute associated with this particular (for parent type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_transaction_particulars', to='core.institute')),
            ],
            options={
                'verbose_name': 'Due Transaction Particular',
                'verbose_name_plural': 'Due Transaction Particulars',
                'db_table': 'due_transaction_particulars',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='duetransaction',
            index=models.Index(fields=['user'], name='due_transac_user_id_2ce8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransaction',
            index=models.Index(fields=['is_paid'], name='due_transac_is_paid_988c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransaction',
            index=models.Index(fields=['expire_date'], name='due_transac_expire__0e4b74_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransaction',
            index=models.Index(fields=['created_at'], name='due_transac_created_01aab1_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransactionparticular',
            index=models.Index(fields=['due_transaction'], name='due_transac_due_tra_3f3505_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransactionparticular',
            index=models.Index(fields=['type'], name='due_transac_type_e66232_idx'),
        ),
        migrations.AddIndex(
            model_name='duetransactionparticular',
            index=models.Index(fields=['institute'], name='due_transac_institu_7fcb3a_idx'),
        ),
    ]
