# Generated by Django 5.2.5 on 2025-11-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        ('finance', '0002_wallet_call_price_wallet_sms_price_duetransaction_and_more'),
        ('fleet', '0007_remove_uservehicle_relay_vehicle_is_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='duetransactionparticular',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column='vehicle_id', help_text='Vehicle associated with this particular (for vehicle type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_transaction_particulars', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='duetransactionparticular',
            index=models.Index(fields=['vehicle'], name='due_transac_vehicle_e5b9ac_idx'),
        ),
    ]
