# Generated by Django 5.2.5 on 2025-11-19 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_duetransactionparticular_vehicle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duetransaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, db_column='paid_by_id', help_text='User who paid for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='duetransaction',
            index=models.Index(fields=['paid_by'], name='due_transac_paid_by_edd7db_idx'),
        ),
    ]
