# Generated by Django 5.2.5 on 2025-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_duetransaction_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duetransactionparticular',
            name='dealer_amount',
            field=models.DecimalField(blank=True, db_column='dealer_amount', decimal_places=2, help_text='Dealer price for this particular', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='duetransactionparticular',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, help_text='Unit amount for this particular (customer price)', max_digits=15),
        ),
    ]
