# Generated by Django 5.2.5 on 2025-11-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_duetransactionparticular_dealer_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txn_id', models.CharField(db_column='txn_id', help_text='Transaction ID from ConnectIPS (TXNID)', max_length=100, unique=True)),
                ('reference_id', models.CharField(db_column='reference_id', help_text='Internal reference ID', max_length=100)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, help_text='Transaction amount in NPR (not paisa)', max_digits=15)),
                ('amount_paisa', models.BigIntegerField(db_column='amount_paisa', help_text='Transaction amount in paisa (for ConnectIPS)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], db_column='status', default='PENDING', help_text='Payment transaction status', max_length=20)),
                ('connectips_response', models.JSONField(blank=True, db_column='connectips_response', help_text='Response from ConnectIPS validation API', null=True)),
                ('connectips_txn_id', models.BigIntegerField(blank=True, db_column='connectips_txn_id', help_text="NCHL's transaction ID from ConnectIPS", null=True)),
                ('connectips_batch_id', models.BigIntegerField(blank=True, db_column='connectips_batch_id', help_text="NCHL's batch ID from ConnectIPS", null=True)),
                ('error_message', models.TextField(blank=True, db_column='error_message', help_text='Error message if payment failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Payment transaction creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Last update timestamp')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', help_text='Payment completion timestamp', null=True)),
                ('user', models.ForeignKey(db_column='user_id', help_text='User who initiated the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(db_column='wallet_id', help_text='Wallet to be credited', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='finance.wallet')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='payment_tra_user_id_b3ceaf_idx'), models.Index(fields=['wallet'], name='payment_tra_wallet__81acfd_idx'), models.Index(fields=['txn_id'], name='payment_tra_txn_id_989c8e_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx')],
            },
        ),
    ]
