# Generated by Django 5.2.5 on 2026-01-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the phone book', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(blank=True, help_text='Institute that owns this phone book (null if owned by user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_books', to='core.institute')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this phone book (null if owned by institute)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Book',
                'verbose_name_plural': 'Phone Books',
                'db_table': 'phone_books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneBookNumber',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contact name', max_length=255)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('phonebook', models.ForeignKey(help_text='Phone book this number belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='phone_call.phonebook')),
            ],
            options={
                'verbose_name': 'Phone Book Number',
                'verbose_name_plural': 'Phone Book Numbers',
                'db_table': 'phone_book_numbers',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='phonebook',
            index=models.Index(fields=['user'], name='phone_books_user_id_fbed44_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebook',
            index=models.Index(fields=['institute'], name='phone_books_institu_3f4303_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebook',
            index=models.Index(fields=['name'], name='phone_books_name_ba936b_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebooknumber',
            index=models.Index(fields=['phonebook'], name='phone_book__phonebo_71a651_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebooknumber',
            index=models.Index(fields=['phone'], name='phone_book__phone_7284e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phonebooknumber',
            unique_together={('phonebook', 'phone')},
        ),
    ]
