# Generated by Django 5.2.5 on 2025-10-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_module_alter_institutemodule_options_and_more'),
        ('device', '0006_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or URL for the alert type', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Alert Type',
                'verbose_name_plural': 'Alert Types',
                'db_table': 'alert_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='alert_types_name_346b63_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertGeofence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('boundary', models.JSONField(help_text='GeoJSON boundary data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this geofence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_geofences', to='core.institute')),
                ('alert_types', models.ManyToManyField(blank=True, help_text='Alert types for this geofence', related_name='alert_geofences', to='alert_system.alerttype')),
            ],
            options={
                'verbose_name': 'Alert Geofence',
                'verbose_name_plural': 'Alert Geofences',
                'db_table': 'alert_geofences',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('is_sms', models.BooleanField(default=True, help_text='Send SMS notifications')),
                ('is_call', models.BooleanField(default=False, help_text='Make phone calls')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_contacts', to='core.institute')),
                ('alert_geofences', models.ManyToManyField(blank=True, help_text='Geofences this contact is associated with', related_name='alert_contacts', to='alert_system.alertgeofence')),
                ('alert_types', models.ManyToManyField(blank=True, help_text='Alert types this contact should be notified about', related_name='alert_contacts', to='alert_system.alerttype')),
            ],
            options={
                'verbose_name': 'Alert Contact',
                'verbose_name_plural': 'Alert Contacts',
                'db_table': 'alert_contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertBuzzer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('delay', models.IntegerField(help_text='Delay in seconds before buzzer activation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('device', models.ForeignKey(help_text='Device associated with this buzzer', on_delete=django.db.models.deletion.CASCADE, related_name='alert_buzzers', to='device.device')),
                ('institute', models.ForeignKey(help_text='Institute this buzzer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_buzzers', to='core.institute')),
                ('alert_geofences', models.ManyToManyField(blank=True, help_text='Geofences that trigger this buzzer', related_name='alert_buzzers', to='alert_system.alertgeofence')),
            ],
            options={
                'verbose_name': 'Alert Buzzer',
                'verbose_name_plural': 'Alert Buzzers',
                'db_table': 'alert_buzzers',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='alert_buzze_title_4f23b8_idx'), models.Index(fields=['institute'], name='alert_buzze_institu_347dcd_idx'), models.Index(fields=['device'], name='alert_buzze_device__de620d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRadar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('token', models.CharField(help_text='Authentication token for radar', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('alert_geofences', models.ManyToManyField(blank=True, help_text='Geofences monitored by this radar', related_name='alert_radars', to='alert_system.alertgeofence')),
                ('institute', models.ForeignKey(help_text='Institute this radar belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_radars', to='core.institute')),
            ],
            options={
                'verbose_name': 'Alert Radar',
                'verbose_name_plural': 'Alert Radars',
                'db_table': 'alert_radars',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='alert_radar_title_819539_idx'), models.Index(fields=['institute'], name='alert_radar_institu_c9ad08_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertSwitch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('trigger', models.IntegerField(help_text='Trigger radius in meters')),
                ('primary_phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, help_text='Switch image', null=True, upload_to='alert_switches/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('device', models.ForeignKey(help_text='Device associated with this switch', on_delete=django.db.models.deletion.CASCADE, related_name='alert_switches', to='device.device')),
                ('institute', models.ForeignKey(help_text='Institute this switch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_switches', to='core.institute')),
            ],
            options={
                'verbose_name': 'Alert Switch',
                'verbose_name_plural': 'Alert Switches',
                'db_table': 'alert_switches',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='alert_switc_title_ad73d5_idx'), models.Index(fields=['institute'], name='alert_switc_institu_1d020c_idx'), models.Index(fields=['device'], name='alert_switc_device__7615d0_idx'), models.Index(fields=['latitude', 'longitude'], name='alert_switc_latitud_af04df_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('app', 'App'), ('switch', 'Switch')], help_text='Source of the alert', max_length=20)),
                ('name', models.CharField(help_text='Name of the person/entity', max_length=255)),
                ('primary_phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('datetime', models.DateTimeField(help_text='Date and time of the alert')),
                ('image', models.ImageField(blank=True, help_text='Alert image', null=True, upload_to='alert_history/')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the alert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this alert belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='core.institute')),
                ('alert_type', models.ForeignKey(help_text='Type of alert', on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='alert_system.alerttype')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'db_table': 'alert_histories',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['source'], name='alert_histo_source_ebe114_idx'), models.Index(fields=['status'], name='alert_histo_status_0fafd7_idx'), models.Index(fields=['institute'], name='alert_histo_institu_ce362a_idx'), models.Index(fields=['datetime'], name='alert_histo_datetim_301892_idx'), models.Index(fields=['alert_type'], name='alert_histo_alert_t_064f74_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertgeofence',
            index=models.Index(fields=['title'], name='alert_geofe_title_ccff33_idx'),
        ),
        migrations.AddIndex(
            model_name='alertgeofence',
            index=models.Index(fields=['institute'], name='alert_geofe_institu_b89bda_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcontact',
            index=models.Index(fields=['name'], name='alert_conta_name_04eb50_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcontact',
            index=models.Index(fields=['phone'], name='alert_conta_phone_37c61d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcontact',
            index=models.Index(fields=['institute'], name='alert_conta_institu_7110c3_idx'),
        ),
    ]
