# Generated by Django 5.2.5 on 2025-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='latitude',
            field=models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='longitude',
            field=models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=13),
        ),
        migrations.AlterField(
            model_name='alertswitch',
            name='latitude',
            field=models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='alertswitch',
            name='longitude',
            field=models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=13),
        ),
    ]
