# Generated by Django 5.2.5 on 2025-10-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0002_alter_alerthistory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('geofence', 'Geofence'), ('switch', 'Switch')], help_text='Source of the alert', max_length=20),
        ),
    ]
