# Generated by Django 5.2.5 on 2025-11-04 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_user_profile_picture'),
        ('fleet', '0004_sharetrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('bus', models.ForeignKey(help_text='Vehicle assigned as school bus', on_delete=django.db.models.deletion.CASCADE, related_name='school_buses', to='fleet.vehicle')),
                ('institute', models.ForeignKey(help_text='Institute this school bus belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='school_buses', to='core.institute')),
            ],
            options={
                'verbose_name': 'School Bus',
                'verbose_name_plural': 'School Buses',
                'db_table': 'school_buses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolParent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Parent location latitude', max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Parent location longitude', max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('parent', models.ForeignKey(help_text='Parent user', on_delete=django.db.models.deletion.CASCADE, related_name='school_parents', to=settings.AUTH_USER_MODEL)),
                ('school_buses', models.ManyToManyField(blank=True, help_text='School buses this parent is associated with', related_name='school_parents', to='school.schoolbus')),
            ],
            options={
                'verbose_name': 'School Parent',
                'verbose_name_plural': 'School Parents',
                'db_table': 'school_parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSMS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='SMS message content')),
                ('phone_numbers', models.JSONField(default=list, help_text='List of phone numbers to send SMS to')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this SMS belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='school_sms', to='core.institute')),
            ],
            options={
                'verbose_name': 'School SMS',
                'verbose_name_plural': 'School SMS',
                'db_table': 'school_sms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolbus',
            index=models.Index(fields=['institute'], name='school_buse_institu_68bd20_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbus',
            index=models.Index(fields=['bus'], name='school_buse_bus_id_35c9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbus',
            index=models.Index(fields=['created_at'], name='school_buse_created_64a336_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolbus',
            unique_together={('institute', 'bus')},
        ),
        migrations.AddIndex(
            model_name='schoolparent',
            index=models.Index(fields=['parent'], name='school_pare_parent__bd862c_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolparent',
            index=models.Index(fields=['latitude', 'longitude'], name='school_pare_latitud_a9a222_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolparent',
            index=models.Index(fields=['created_at'], name='school_pare_created_3f704d_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsms',
            index=models.Index(fields=['institute'], name='school_sms_institu_896703_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsms',
            index=models.Index(fields=['created_at'], name='school_sms_created_e0a0be_idx'),
        ),
    ]
