# Generated by Django 5.2.5 on 2025-11-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolparent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Parent location latitude', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='schoolparent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Parent location longitude', max_digits=19, null=True),
        ),
    ]
