# Generated by Django 5.2.5 on 2025-11-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoolparent_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolparent',
            name='child_name',
            field=models.CharField(blank=True, help_text='Child name', max_length=255, null=True),
        ),
    ]
