# Generated by Django 5.2.5 on 2025-11-17 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_add_child_name_to_schoolparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolparent',
            index=models.Index(fields=['parent', 'child_name'], name='school_parent_p_cn_idx'),
        ),
    ]
