# Generated by Django 5.2.5 on 2025-09-15 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit')], max_length=20)),
                ('boundary', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'geofences',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(db_column='is_active', default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'popups',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('all', 'All'), ('specific', 'Specific')], max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('sentBy', models.ForeignKey(db_column='sent_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='sentNotifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='device.device')),
            ],
            options={
                'db_table': 'recharges',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isRead', models.BooleanField(db_column='is_read', default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userNotifications', to='shared.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userNotifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notifications',
            },
        ),
        migrations.CreateModel(
            name='GeofenceUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.geofence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geofence_users',
                'unique_together': {('geofence', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'createdAt'], name='notificatio_type_cb6908_idx'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['device'], name='recharges_device__b42400_idx'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['createdAt'], name='recharges_created_c4bb98_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'isRead'], name='user_notifi_user_id_ea6762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
    ]
