# Generated by Django 5.2.5 on 2025-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_recharge_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popup'),
        ),
    ]
