# Generated by Django 5.2.5 on 2025-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_popup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('all', 'All'), ('specific', 'Specific'), ('role', 'Role')], max_length=20),
        ),
    ]
