# Generated by Django 5.2.5 on 2025-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_notification_updatedat_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField(db_column='vehicle_id', help_text='Vehicle ID from vehicles table')),
                ('geofence_id', models.IntegerField(db_column='geofence_id', help_text='Geofence ID from geofences table')),
                ('is_inside', models.BooleanField(db_column='is_inside', default=False, help_text='Current state: True if inside, False if outside')),
                ('last_event_type', models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit')], db_column='last_event_type', help_text='Last event type: Entry or Exit', max_length=10)),
                ('last_event_at', models.DateTimeField(db_column='last_event_at', help_text='Timestamp of last event')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'geofence_events',
                'indexes': [models.Index(fields=['vehicle_id', 'geofence_id'], name='geofence_ev_vehicle_71ca4d_idx'), models.Index(fields=['last_event_at'], name='geofence_ev_last_ev_76bbaa_idx')],
                'unique_together': {('vehicle_id', 'geofence_id')},
            },
        ),
    ]
