# Generated by Django 5.2.5 on 2025-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAppLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'External App Link',
                'verbose_name_plural': 'External App Links',
                'db_table': 'external_app_links',
                'ordering': ['name'],
            },
        ),
    ]
