# Generated by Django 5.2.5 on 2025-11-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_externalapplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapplink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalapplink',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='external_app_logos/'),
        ),
        migrations.AlterField(
            model_name='externalapplink',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalapplink',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
