# Generated by Django 5.2.5 on 2025-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_externalapplink_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('url', models.URLField(max_length=500)),
                ('isActive', models.BooleanField(db_column='is_active', default=True)),
                ('click', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
