# Generated by Django 5.2.5 on 2025-11-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
