# Generated by Django 5.2.5 on 2025-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_alter_banner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orderPosition', '-createdAt']},
        ),
        migrations.AddField(
            model_name='banner',
            name='orderPosition',
            field=models.IntegerField(db_column='order_position', default=0),
        ),
    ]
