# Generated by Django 5.2.5 on 2025-12-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_devicecart_devicecartitem_and_more'),
        ('shared', '0011_alter_banner_options_banner_orderposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number (SIM number)', max_length=20)),
                ('state', models.CharField(default='ACTIVE', help_text='SIM state (ACTIVE, INACTIVE, etc.)', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Account balance', max_digits=10)),
                ('balance_expiry', models.DateTimeField(blank=True, help_text='Balance expiry date', null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True, db_column='last_synced_at', help_text='Last sync timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('device', models.OneToOneField(blank=True, help_text='Linked device (can be null if device not found during import)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_balance', to='device.device')),
            ],
            options={
                'verbose_name': 'SIM Balance',
                'verbose_name_plural': 'SIM Balances',
                'db_table': 'sim_balances',
            },
        ),
        migrations.CreateModel(
            name='SimFreeResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Resource name (e.g., 'm2m 50mb', '15 Pcs')", max_length=255)),
                ('resource_type', models.CharField(choices=[('DATA', 'Data'), ('SMS', 'SMS'), ('VOICE', 'Voice')], help_text='Type of resource (DATA, SMS, VOICE)', max_length=20)),
                ('remaining', models.CharField(help_text="Remaining amount (e.g., '49.83MB', '15 Pcs', '40 Min')", max_length=100)),
                ('expiry', models.DateTimeField(help_text='Resource expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('sim_balance', models.ForeignKey(help_text='Associated SIM balance', on_delete=django.db.models.deletion.CASCADE, related_name='free_resources', to='shared.simbalance')),
            ],
            options={
                'verbose_name': 'SIM Free Resource',
                'verbose_name_plural': 'SIM Free Resources',
                'db_table': 'sim_free_resources',
            },
        ),
        migrations.AddIndex(
            model_name='simbalance',
            index=models.Index(fields=['phone_number'], name='sim_balance_phone_n_c167a4_idx'),
        ),
        migrations.AddIndex(
            model_name='simbalance',
            index=models.Index(fields=['balance_expiry'], name='sim_balance_balance_ca4dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='simbalance',
            index=models.Index(fields=['state'], name='sim_balance_state_d9f354_idx'),
        ),
        migrations.AddIndex(
            model_name='simfreeresource',
            index=models.Index(fields=['sim_balance', 'resource_type'], name='sim_free_re_sim_bal_db17e0_idx'),
        ),
        migrations.AddIndex(
            model_name='simfreeresource',
            index=models.Index(fields=['expiry'], name='sim_free_re_expiry_cc0512_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simfreeresource',
            unique_together={('sim_balance', 'name', 'expiry')},
        ),
    ]
