# Generated by Django 5.2.5 on 2025-12-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_simbalance_simfreeresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simfreeresource',
            name='data_plan_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Data plan MB value extracted from name (e.g., 50 from 'm2m 50mb')", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simfreeresource',
            name='remaining_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Remaining MB value extracted from remaining field (e.g., 49.83 from '49.83MB')", max_digits=10, null=True),
        ),
    ]
