# Generated by Django migration
from django.db import migrations, models
import django.db.models.deletion


def migrate_free_resources_to_simbalance(apps, schema_editor):
    """Migrate MB data from SimFreeResource to SimBalance"""
    SimBalance = apps.get_model('shared', 'SimBalance')
    SimFreeResource = apps.get_model('shared', 'SimFreeResource')
    
    # For each SimBalance, find the latest DATA resource and migrate it
    for sim_balance in SimBalance.objects.all():
        try:
            # Get the latest DATA resource with latest expiry
            latest_resource = SimFreeResource.objects.filter(
                sim_balance=sim_balance,
                resource_type='DATA'
            ).order_by('-expiry').first()
            
            if latest_resource:
                sim_balance.mb = latest_resource.data_plan_mb
                sim_balance.remaining_mb = latest_resource.remaining_mb
                sim_balance.mb_expiry_date = latest_resource.expiry
                sim_balance.save()
        except Exception:
            # If migration fails for a record, continue with others
            pass


def reverse_migration(apps, schema_editor):
    """Reverse migration - not implemented as SimFreeResource will be deleted"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_add_data_mb_fields_to_sim_free_resource'),
    ]

    operations = [
        # Add new fields to SimBalance
        migrations.AddField(
            model_name='simbalance',
            name='mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total MB plan value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simbalance',
            name='remaining_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining MB', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simbalance',
            name='mb_expiry_date',
            field=models.DateTimeField(blank=True, help_text='MB data expiry date', null=True),
        ),
        # Migrate data from SimFreeResource to SimBalance
        migrations.RunPython(migrate_free_resources_to_simbalance, reverse_migration),
        # Add index for mb_expiry_date
        migrations.AddIndex(
            model_name='simbalance',
            index=models.Index(fields=['mb_expiry_date'], name='shared_simb_mb_expi_idx'),
        ),
        # Delete SimFreeResource model
        migrations.DeleteModel(
            name='SimFreeResource',
        ),
    ]
