# Generated by Django 5.2.5 on 2026-01-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_remove_simfreeresource_add_mb_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='simbalance',
            new_name='sim_balance_mb_expi_f26ab2_idx',
            old_name='shared_simb_mb_expi_idx',
        ),
    ]
