# Generated by Django 5.2.5 on 2025-09-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('apply_type', models.CharField(choices=[('need', 'Need'), ('donate', 'Donate')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('last_donated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blood_donations',
            },
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recharges',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='locations_imei_29cb5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='statuses_imei_e1b40f_idx',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='iccid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.device', to_field='imei'),
        ),
        migrations.AlterField(
            model_name='status',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app.device', to_field='imei'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.role'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='app.device', to_field='imei'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['imei', 'created_at'], name='locations_imei_4561bb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['speed'], name='locations_speed_fa4674_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['imei', 'created_at'], name='statuses_imei_afa99f_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['imei', 'ignition'], name='statuses_imei_033df1_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['battery'], name='statuses_battery_6a371c_idx'),
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['user'], name='user_vehicl_user_id_f17eee_idx'),
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['vehicle'], name='user_vehicl_vehicle_b54058_idx'),
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['user', 'is_main'], name='user_vehicl_user_id_406742_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['imei'], name='vehicles_imei_892831_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at'], name='vehicles_created_b41437_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['apply_type'], name='blood_donat_apply_t_d9a7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['blood_group'], name='blood_donat_blood_g_0f0caa_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['status'], name='blood_donat_status_d819f8_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['created_at'], name='blood_donat_created_d19dc1_idx'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='app.device'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPermissions', to='app.user'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['device'], name='recharges_device__b42400_idx'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['created_at'], name='recharges_created_c4bb98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
