# Generated by Django 5.2.5 on 2025-12-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vtid', models.CharField(db_column='vtid', help_text='Vehicle Tag ID in format VTID{id}', max_length=50, unique=True)),
                ('vehicle_model', models.CharField(blank=True, db_column='vehicle_model', help_text='Model of the vehicle', max_length=255, null=True)),
                ('registration_no', models.CharField(blank=True, db_column='registration_no', help_text='Vehicle registration number', max_length=255, null=True)),
                ('register_type', models.CharField(blank=True, choices=[('traditional_old', 'Traditional Old'), ('traditional_new', 'Traditional New'), ('embossed', 'Embossed')], db_column='register_type', help_text='Type of registration', max_length=50, null=True)),
                ('vehicle_category', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('government', 'Government'), ('diplomats', 'Diplomats'), ('non_profit_org', 'Non Profit Organization'), ('corporation', 'Corporation'), ('tourism', 'Tourism'), ('ministry', 'Ministry')], db_column='vehicle_category', help_text='Category of the vehicle', max_length=50, null=True)),
                ('sos_number', models.CharField(blank=True, db_column='sos_number', help_text='SOS contact number', max_length=50, null=True)),
                ('sms_number', models.CharField(blank=True, db_column='sms_number', help_text='SMS contact number', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Whether the tag is active')),
                ('is_downloaded', models.BooleanField(db_column='is_downloaded', default=False, help_text='Whether the tag has been downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this vehicle tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Tag',
                'verbose_name_plural': 'Vehicle Tags',
                'db_table': 'vehicle_tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTagAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, help_text='Latitude where alert was reported', max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, help_text='Longitude where alert was reported', max_digits=19, null=True)),
                ('person_image', models.ImageField(blank=True, db_column='person_image', help_text='Image of person reporting the alert', null=True, upload_to='vehicle_tag_alerts/')),
                ('alert', models.CharField(choices=[('wrong_parking', 'Wrong Parking'), ('blocking_road', 'Blocking the road'), ('not_locked_ignition_on', 'Not Locked / Ignition ON'), ('vehicle_tow_alert', 'Vehicle Tow Alert'), ('traffic_rule_violation', 'Traffic Rule Violation'), ('fire_physical_threat', 'Fire & Physical Threat'), ('accident_alert', 'Accident Alert (Inform Family)')], db_column='alert', help_text='Type of alert', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle_tag', models.ForeignKey(db_column='vehicle_tag_vtid', help_text='Vehicle tag this alert is for', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicle_tag.vehicletag', to_field='vtid')),
            ],
            options={
                'verbose_name': 'Vehicle Tag Alert',
                'verbose_name_plural': 'Vehicle Tag Alerts',
                'db_table': 'vehicle_tag_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTagUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vtid', models.CharField(db_column='vtid', help_text='Vehicle Tag ID for quick reference', max_length=50)),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Whether this assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(help_text='User assigned to this vehicle tag', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tag_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle_tag', models.ForeignKey(db_column='vehicle_tag_id', help_text='Vehicle tag being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='tag_users', to='vehicle_tag.vehicletag')),
            ],
            options={
                'verbose_name': 'Vehicle Tag User',
                'verbose_name_plural': 'Vehicle Tag Users',
                'db_table': 'vehicle_tag_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicletag',
            index=models.Index(fields=['vtid'], name='vehicle_tag_vtid_8c458f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletag',
            index=models.Index(fields=['user'], name='vehicle_tag_user_id_22f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletag',
            index=models.Index(fields=['is_active'], name='vehicle_tag_is_acti_981ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletag',
            index=models.Index(fields=['created_at'], name='vehicle_tag_created_22105e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletagalert',
            index=models.Index(fields=['vehicle_tag'], name='vehicle_tag_vehicle_03d998_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletagalert',
            index=models.Index(fields=['alert'], name='vehicle_tag_alert_29f1db_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletagalert',
            index=models.Index(fields=['created_at'], name='vehicle_tag_created_287cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletaguser',
            index=models.Index(fields=['vehicle_tag'], name='vehicle_tag_vehicle_5335d9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletaguser',
            index=models.Index(fields=['user'], name='vehicle_tag_user_id_162fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletaguser',
            index=models.Index(fields=['vtid'], name='vehicle_tag_vtid_010e91_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletaguser',
            index=models.Index(fields=['is_active'], name='vehicle_tag_is_acti_e6e757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletaguser',
            unique_together={('vehicle_tag', 'user')},
        ),
    ]
