# Generated by Django 5.2.5 on 2025-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletag',
            name='visit_count',
            field=models.IntegerField(db_column='visit_count', default=0, help_text='Number of times the vehicle tag has been accessed/viewed'),
        ),
        migrations.AddField(
            model_name='vehicletagalert',
            name='sms_sent',
            field=models.BooleanField(db_column='sms_sent', default=False, help_text='Whether SMS was sent for this alert'),
        ),
    ]
