# Generated by Django 5.2.5 on 2025-11-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_institutemodule_expire_date_and_more'),
        ('fleet', '0008_vehicle_number_plate_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageVehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('institute', models.ForeignKey(help_text='Institute this garbage vehicle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='garbage_vehicles', to='core.institute')),
                ('vehicle', models.ForeignKey(help_text='Vehicle assigned as garbage vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='garbage_vehicles', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Garbage Vehicle',
                'verbose_name_plural': 'Garbage Vehicles',
                'db_table': 'garbage_vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institute'], name='garbage_veh_institu_f77a36_idx'), models.Index(fields=['vehicle'], name='garbage_veh_vehicle_a73d38_idx'), models.Index(fields=['created_at'], name='garbage_veh_created_e0b2ce_idx')],
                'unique_together': {('institute', 'vehicle')},
            },
        ),
    ]
