# Generated by Django 5.2.5 on 2025-09-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
