# Generated by Django 5.2.5 on 2025-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='relay',
            field=models.BooleanField(default=False),
        ),
    ]
