# Generated by Django 5.2.5 on 2025-10-10 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_uservehicle_relay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(help_text='Vehicle IMEI number', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(help_text='When this share will expire')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share is still active')),
                ('user', models.ForeignKey(help_text='User who created the share', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Track',
                'verbose_name_plural': 'Share Tracks',
                'db_table': 'share_track',
                'indexes': [models.Index(fields=['imei'], name='share_track_imei_eb2e97_idx'), models.Index(fields=['token'], name='share_track_token_9b41ea_idx'), models.Index(fields=['scheduled_for'], name='share_track_schedul_2dde0b_idx'), models.Index(fields=['is_active'], name='share_track_is_acti_9af28a_idx')],
            },
        ),
    ]
