# Generated by Django 5.2.5 on 2025-11-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_expire_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_expire_active_idx',
        ),
    ]
