# Generated by Django 5.2.5 on 2025-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_vehicle_vehicles_expire_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservehicle',
            name='relay',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_relay',
            field=models.BooleanField(db_column='is_relay', default=False),
        ),
    ]
