# Generated by Django 5.2.5 on 2025-11-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_remove_uservehicle_relay_vehicle_is_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='number_plate_photo',
            field=models.ImageField(blank=True, db_column='number_plate_photo', null=True, upload_to='vehicles/number_plates/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='servicing_distance_period',
            field=models.IntegerField(db_column='servicing_distance_period', default=10000, help_text='Distance in kilometers between servicing'),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document type (e.g., Blue Book, License, Insurance)', max_length=255)),
                ('last_expire_date', models.DateField(db_column='last_expire_date')),
                ('expire_in_month', models.IntegerField(db_column='expire_in_month', help_text='Expiry period in months')),
                ('document_image_one', models.ImageField(blank=True, db_column='document_image_one', null=True, upload_to='vehicles/documents/')),
                ('document_image_two', models.ImageField(blank=True, db_column='document_image_two', null=True, upload_to='vehicles/documents/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'ordering': ['-last_expire_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_doc_vehicle_4d8afa_idx'), models.Index(fields=['last_expire_date'], name='vehicle_doc_last_ex_e44f12_idx'), models.Index(fields=['title'], name='vehicle_doc_title_a4184d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleEnergyCost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('energy_type', models.CharField(choices=[('fuel', 'Fuel'), ('electric', 'Electric')], db_column='energy_type', max_length=20)),
                ('entry_date', models.DateField(db_column='entry_date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_unit', models.DecimalField(db_column='total_unit', decimal_places=2, help_text='Total units (liters/kWh)', max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='energy_costs', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'vehicle_energy_costs',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_ene_vehicle_8c8a3a_idx'), models.Index(fields=['entry_date'], name='vehicle_ene_entry_d_572ec2_idx'), models.Index(fields=['energy_type'], name='vehicle_ene_energy__8d7731_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('expenses_type', models.CharField(choices=[('part', 'Part'), ('fine', 'Fine')], db_column='expenses_type', max_length=20)),
                ('entry_date', models.DateField(db_column='entry_date')),
                ('part_expire_month', models.IntegerField(blank=True, db_column='part_expire_month', help_text='Expiry month for parts', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'vehicle_expenses',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_exp_vehicle_9887ee_idx'), models.Index(fields=['entry_date'], name='vehicle_exp_entry_d_a15882_idx'), models.Index(fields=['expenses_type'], name='vehicle_exp_expense_ec47db_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleServicing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicings', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'vehicle_servicings',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_ser_vehicle_ac08ac_idx'), models.Index(fields=['date'], name='vehicle_ser_date_616569_idx')],
            },
        ),
    ]
