# Generated by Django 5.2.5 on 2025-09-15 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('sim', models.CharField(choices=[('NTC', 'NTC'), ('Ncell', 'Ncell')], max_length=10)),
                ('protocol', models.CharField(choices=[('GT06', 'GT06'), ('FMB003', 'FMB003')], default='GT06', max_length=10)),
                ('iccid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('model', models.CharField(choices=[('EC08', 'EC08'), ('VL149', 'VL149')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'devices',
                'indexes': [models.Index(fields=['imei'], name='devices_imei_fa0ada_idx'), models.Index(fields=['phone'], name='devices_phone_89a423_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed', models.IntegerField()),
                ('course', models.IntegerField()),
                ('realTimeGps', models.BooleanField(db_column='real_time_gps')),
                ('satellite', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='device.device', to_field='imei')),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['imei', 'createdAt'], name='locations_imei_4561bb_idx'), models.Index(fields=['createdAt'], name='locations_created_146821_idx'), models.Index(fields=['latitude', 'longitude'], name='locations_latitud_4052bd_idx'), models.Index(fields=['speed'], name='locations_speed_fa4674_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15)),
                ('battery', models.IntegerField()),
                ('signal', models.IntegerField()),
                ('ignition', models.BooleanField()),
                ('charging', models.BooleanField()),
                ('relay', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='device.device', to_field='imei')),
            ],
            options={
                'db_table': 'statuses',
                'indexes': [models.Index(fields=['imei', 'createdAt'], name='statuses_imei_afa99f_idx'), models.Index(fields=['imei', 'ignition'], name='statuses_imei_033df1_idx'), models.Index(fields=['createdAt'], name='statuses_created_e42e12_idx'), models.Index(fields=['battery'], name='statuses_battery_6a371c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDevices', to='device.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDevices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
                'unique_together': {('user', 'device')},
            },
        ),
    ]
