# Generated by Django 5.2.5 on 2025-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='createdAt',
            field=models.DateTimeField(db_column='created_at'),
        ),
    ]
