# Generated by Django 5.2.5 on 2025-10-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('device', '0002_alter_location_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'subscription_plans',
                'indexes': [models.Index(fields=['title'], name='subscriptio_title_288b2c_idx'), models.Index(fields=['price'], name='subscriptio_price_704aa0_idx')],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_permissions', to='auth.permission')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='device.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_plan_permissions',
                'indexes': [models.Index(fields=['permission', 'subscription_plan'], name='subscriptio_permiss_85d886_idx'), models.Index(fields=['subscription_plan'], name='subscriptio_subscri_9642f5_idx')],
                'unique_together': {('permission', 'subscription_plan')},
            },
        ),
    ]
