# Generated by Django 5.2.5 on 2025-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_subscriptionplan_device_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AddField(
            model_name='status',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['updatedAt'], name='locations_updated_14c798_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['updatedAt'], name='statuses_updated_42dccc_idx'),
        ),
    ]
