# Generated by Django 5.2.5 on 2025-10-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_location_updatedat_status_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updatedAt',
            field=models.DateTimeField(db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='status',
            name='updatedAt',
            field=models.DateTimeField(db_column='updated_at'),
        ),
    ]
