# Generated by Django 5.2.5 on 2025-10-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_location_updatedat_alter_status_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('buzzer', 'Buzzer'), ('sos', 'SOS')], default='gps', max_length=10, null=True),
        ),
    ]
