# Generated by Django 5.2.5 on 2025-10-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('speed', models.IntegerField()),
                ('realTimeGps', models.BooleanField(db_column='real_time_gps')),
                ('course', models.IntegerField()),
                ('satellite', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('signal', models.IntegerField()),
                ('alarm', models.CharField(choices=[('normal', 'Normal'), ('sos', 'SOS'), ('power_cut', 'Power Cut'), ('shock', 'Shock'), ('fence_in', 'Fence In'), ('fence_out', 'Fence Out')], max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(db_column='updated_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_data', to='device.device', to_field='imei')),
            ],
            options={
                'db_table': 'alarm_data',
                'indexes': [models.Index(fields=['imei', 'createdAt'], name='alarm_data_imei_18a982_idx'), models.Index(fields=['imei', 'alarm'], name='alarm_data_imei_202ab9_idx'), models.Index(fields=['createdAt'], name='alarm_data_created_d85052_idx'), models.Index(fields=['updatedAt'], name='alarm_data_updated_fa1e5b_idx'), models.Index(fields=['latitude', 'longitude'], name='alarm_data_latitud_a4e69c_idx'), models.Index(fields=['alarm'], name='alarm_data_alarm_f2b315_idx'), models.Index(fields=['speed'], name='alarm_data_speed_3f3fbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuzzerStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15)),
                ('battery', models.IntegerField()),
                ('signal', models.IntegerField()),
                ('ignition', models.BooleanField()),
                ('charging', models.BooleanField()),
                ('relay', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(db_column='updated_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzer_statuses', to='device.device', to_field='imei')),
            ],
            options={
                'db_table': 'buzzer_status',
                'indexes': [models.Index(fields=['imei', 'createdAt'], name='buzzer_stat_imei_9f5a8d_idx'), models.Index(fields=['imei', 'ignition'], name='buzzer_stat_imei_fcb4ea_idx'), models.Index(fields=['createdAt'], name='buzzer_stat_created_d4cdb6_idx'), models.Index(fields=['updatedAt'], name='buzzer_stat_updated_4eb3c8_idx'), models.Index(fields=['battery'], name='buzzer_stat_battery_e2918e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SosStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15)),
                ('battery', models.IntegerField()),
                ('signal', models.IntegerField()),
                ('ignition', models.BooleanField()),
                ('charging', models.BooleanField()),
                ('relay', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(db_column='updated_at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_statuses', to='device.device', to_field='imei')),
            ],
            options={
                'db_table': 'sos_switch_status',
                'indexes': [models.Index(fields=['imei', 'createdAt'], name='sos_switch__imei_e1449f_idx'), models.Index(fields=['imei', 'ignition'], name='sos_switch__imei_b2c353_idx'), models.Index(fields=['createdAt'], name='sos_switch__created_04a70a_idx'), models.Index(fields=['updatedAt'], name='sos_switch__updated_ad28fc_idx'), models.Index(fields=['battery'], name='sos_switch__battery_dcb01b_idx')],
            },
        ),
    ]
