# Generated by Django 5.2.5 on 2025-11-09 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alarmdata_buzzerstatus_sosstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunaTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publicKey', models.CharField(db_column='public_key', max_length=255, unique=True)),
                ('is_lost_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'luna_tags',
                'indexes': [models.Index(fields=['publicKey'], name='luna_tags_public__d9c4f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LunaTagData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('battery', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicKey', models.ForeignKey(db_column='public_key', on_delete=django.db.models.deletion.CASCADE, related_name='lunaTagData', to='device.lunatag', to_field='publicKey')),
            ],
            options={
                'db_table': 'luna_tag_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['publicKey'], name='luna_tag_da_public__47cf9a_idx'), models.Index(fields=['created_at'], name='luna_tag_da_created_b5d313_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLunaTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/luna_tags/')),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicKey', models.ForeignKey(db_column='public_key', on_delete=django.db.models.deletion.CASCADE, related_name='userLunaTags', to='device.lunatag', to_field='publicKey')),
            ],
            options={
                'db_table': 'user_luna_tags',
                'indexes': [models.Index(fields=['publicKey'], name='user_luna_t_public__ceb60a_idx'), models.Index(fields=['is_active'], name='user_luna_t_is_acti_b9bfbf_idx')],
            },
        ),
    ]
