# Generated by Django 5.2.5 on 2025-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_lunatag_lunatagdata_userlunatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='dealer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
