# Generated by Django 5.2.5 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_subscriptionplan_dealer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='purchasing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]

