# Generated by Django 5.2.5 on 2025-11-20 00:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_subscriptionplan_purchasing_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('preparing', 'Preparing'), ('dispatch', 'Dispatch')], db_column='status', default='accepted', help_text='Order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], db_column='payment_status', default='pending', help_text='Payment status', max_length=20)),
                ('sub_total', models.DecimalField(db_column='sub_total', decimal_places=2, help_text='Subtotal amount before VAT', max_digits=15)),
                ('is_vat', models.BooleanField(db_column='is_vat', default=False, help_text='Whether VAT is applicable')),
                ('vat', models.DecimalField(db_column='vat', decimal_places=2, default=Decimal('0.00'), help_text='VAT amount (13%)', max_digits=15)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, help_text='Total amount including VAT', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Order creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Last order update timestamp')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='device_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Order',
                'verbose_name_plural': 'Device Orders',
                'db_table': 'device_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, help_text='Price per unit (purchasing_price from subscription plan)', max_digits=10)),
                ('quantity', models.IntegerField(db_column='quantity', help_text='Quantity of devices ordered')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, help_text='Total amount (price * quantity)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Item creation timestamp')),
                ('device_order', models.ForeignKey(db_column='device_order_id', help_text='The device order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='device.deviceorder')),
                ('subscription_plan', models.ForeignKey(db_column='subscription_plan_id', help_text='Subscription plan (device product) for this order item', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='device.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Device Order Item',
                'verbose_name_plural': 'Device Order Items',
                'db_table': 'device_order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceorder',
            index=models.Index(fields=['user'], name='device_orde_user_id_dfafec_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceorder',
            index=models.Index(fields=['status'], name='device_orde_status_c2beaa_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceorder',
            index=models.Index(fields=['payment_status'], name='device_orde_payment_814607_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceorder',
            index=models.Index(fields=['created_at'], name='device_orde_created_32e9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceorderitem',
            index=models.Index(fields=['device_order'], name='device_orde_device__0dbf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceorderitem',
            index=models.Index(fields=['subscription_plan'], name='device_orde_subscri_9db41e_idx'),
        ),
    ]
