# Generated by Django 5.2.5 on 2025-11-20 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_deviceorder_deviceorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='device_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of devices to order')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit (snapshot of purchasing_price at time of add)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('cart', models.ForeignKey(db_column='cart_id', help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='device.devicecart')),
                ('subscription_plan', models.ForeignKey(db_column='subscription_plan_id', help_text='Subscription plan being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='device.subscriptionplan')),
            ],
            options={
                'db_table': 'device_cart_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicecart',
            index=models.Index(fields=['user'], name='device_cart_user_id_46f587_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecart',
            index=models.Index(fields=['updated_at'], name='device_cart_updated_d78752_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecartitem',
            index=models.Index(fields=['cart'], name='device_cart_cart_id_cd2c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecartitem',
            index=models.Index(fields=['subscription_plan'], name='device_cart_subscri_e72e93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecartitem',
            unique_together={('cart', 'subscription_plan')},
        ),
    ]
