# Generated by Django 5.2.5 on 2026-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_devicecart_devicecartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(choices=[('EC08', 'EC08'), ('VL149', 'VL149'), ('T98_BSJ', 'T98/BSJ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('GT06', 'GT06'), ('FMB003', 'FMB003'), ('JT808_JT1078', 'JT808/JT1078')], default='GT06', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('buzzer', 'Buzzer'), ('sos', 'SOS'), ('dashcam', 'Dashcam')], default='gps', max_length=10, null=True),
        ),
    ]
