# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashcamLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('direction', models.IntegerField(default=0)),
                ('satellite', models.IntegerField(default=0)),
                ('alarm_flags', models.BigIntegerField(default=0)),
                ('status_flags', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'dashcam_locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashcamStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=15)),
                ('battery', models.IntegerField(default=0)),
                ('signal', models.IntegerField(default=0)),
                ('recording', models.BooleanField(default=False)),
                ('sd_status', models.CharField(default='unknown', max_length=20)),
                ('front_camera', models.BooleanField(default=True)),
                ('rear_camera', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'dashcam_statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashcamStream',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=15)),
                ('channel', models.IntegerField(default=1)),
                ('is_streaming', models.BooleanField(default=False)),
                ('stream_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('codec', models.CharField(default='avc1.640028', max_length=20)),
                ('width', models.IntegerField(default=1280)),
                ('height', models.IntegerField(default=720)),
                ('fps', models.IntegerField(default=25)),
                ('viewer_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'dashcam_streams',
            },
        ),
        migrations.CreateModel(
            name='DashcamConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=15, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('auth_code', models.CharField(blank=True, default='', max_length=32)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'dashcam_connections',
            },
        ),
        migrations.AddIndex(
            model_name='dashcamlocation',
            index=models.Index(fields=['imei'], name='dashcam_loc_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamlocation',
            index=models.Index(fields=['imei', 'created_at'], name='dashcam_loc_imei_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamstatus',
            index=models.Index(fields=['imei'], name='dashcam_stat_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamstatus',
            index=models.Index(fields=['imei', 'created_at'], name='dashcam_stat_imei_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamstream',
            index=models.Index(fields=['imei'], name='dashcam_stream_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamstream',
            index=models.Index(fields=['imei', 'channel'], name='dashcam_stream_imei_chan_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamstream',
            index=models.Index(fields=['stream_key'], name='dashcam_stream_key_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamconnection',
            index=models.Index(fields=['imei'], name='dashcam_conn_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='dashcamconnection',
            index=models.Index(fields=['is_connected'], name='dashcam_conn_connected_idx'),
        ),
    ]
