# Generated by Django 5.2.5 on 2026-01-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcp_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashcamconnection',
            new_name='dashcam_con_imei_5a75d1_idx',
            old_name='dashcam_conn_imei_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamconnection',
            new_name='dashcam_con_is_conn_b239a1_idx',
            old_name='dashcam_conn_connected_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamlocation',
            new_name='dashcam_loc_imei_f212f4_idx',
            old_name='dashcam_loc_imei_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamlocation',
            new_name='dashcam_loc_imei_091ba2_idx',
            old_name='dashcam_loc_imei_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamstatus',
            new_name='dashcam_sta_imei_edfd44_idx',
            old_name='dashcam_stat_imei_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamstatus',
            new_name='dashcam_sta_imei_221d12_idx',
            old_name='dashcam_stat_imei_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamstream',
            new_name='dashcam_str_imei_e4dfe4_idx',
            old_name='dashcam_stream_imei_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamstream',
            new_name='dashcam_str_imei_602c4d_idx',
            old_name='dashcam_stream_imei_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='dashcamstream',
            new_name='dashcam_str_stream__eb982a_idx',
            old_name='dashcam_stream_key_idx',
        ),
    ]
