"""
Django settings for luna_iot_py project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, pymysql

pymysql.install_as_MySQLdb()

# Load environment variables from .env file if it exists (optional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0^#(66z3-wsvc(hvc)6gw20)2k!rz3$_68fh)b!mmrhn82awc7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Core modules
    'core',
    'shared',
    'device',
    'fleet',
    'health',
    
    
    # Third party
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'api_common.middleware.cors_middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api_common.middleware.disable_csrf_middleware.DisableCSRFMiddleware',  # Disable CSRF for API
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api_common.middleware.auth_middleware.AuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'luna_iot_py.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-phone',
    'x-token',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF completely disabled for API
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = None
CSRF_TRUSTED_ORIGINS = []

# Custom User Model
AUTH_USER_MODEL = 'core.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luna_iot_py.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'luna_iot_test',
        'USER': 'root', 
        'PASSWORD': '214fa86d5dfe4729', 
        'HOST': '38.54.71.218', 
        # 'HOST': 'localhost', 
        'PORT': '3306',
        'OPTIONS': {
            'connect_timeout': 60,
            'read_timeout': 60,
            'write_timeout': 60,
        }
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static')
# ] 
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SMS Configuration
SMS_API_KEY = '568383D0C5AA82'
SMS_API_URL = 'https://sms.kaichogroup.com/smsapi/index.php'
SMS_CAMPAIGN_ID = '9148'
SMS_ROUTE_ID = '130'
SMS_SENDER_ID = 'SMSBit'

# Firebase Configuration
FIREBASE_PROJECT_ID = "luna-iot-5993f"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@luna-iot-5993f.iam.gserviceaccount.com"
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLIZj/7sNBH8KU\nAGGg0PorZAkRfPvASkAtJ9mMvatoWXOB3zldwys1yajsMwydt1UQk2wPSp7pC68R\nRdSwy8dA6SGKgW0iuK6uLQdF0YzXcn/Wqkin0p2Bv1thVTukg5rkWyc7YSaLMqtp\nh+X2VM27IhzXAE+ZNUXn/eZejlbMkTjO5L8bxwynjWVLdsT0DA5iFidFqEp3b0tu\nOu1CvKFum1n3OO/cDqjTXkYvHa6CRGv3iOKQ9pMvYu2Voo1uL8pbohdKarNLPr9O\nhMb+Pm227lrzGunRJYNO/E/Q+FAchGtbgdJnRj0iJg4nYATSbtLHh6Bg6gfH/d8U\nc5WM8XApAgMBAAECggEAEqLuu15vxhAQpU0CqAM8TJJVPahCnbICQNJU5JN7QCvi\ny9HL3NUc6AasK52EZQzurkJkSePeAAIdKf/G44CSs5sgA2nb9jFM/3hsoCR5YEPm\nRC7j0xfg8Qg6LUwpWG7lnVlamFlRtLgtn1VDTS4bIPXggP5Lj0Iiu4XhJqA3CPYI\n+TU6mHw8SkFtPbe+Q1rz4bEofsISu2b9l/BsVOgUOdV/tmEPn/x+9/RNV3A8U0ma\nk0nAzhIKbjHZkAGPCcUk+OJckMZscU8KOMZJdYStMB1y99aM/IurBwlTrD24BKWS\nelyZOESJEfMoy7XxkbITuaKMzkO5ff9pLL33CeKJ7QKBgQDzvUAtu3Xz7NigJwfb\nJKaNo/I16OvcIVhk4Kmmn4ea34XGU0hsWH5XiQhE+SAGRhJSowSsLUoDDg8yv2me\n4et/MABEq92XV2dSG/Z7Q09swq1fCmBTY+rom3AVt8nH55ap5gqj0dCv5sE6Vgwn\nu713lxcVxL/5dqu4qfQEe539nQKBgQDVWWrtlk+CckZZT9yUa119DcGVdxEHwrlJ\nT7xJosDUXYQaQA4E05HlEFXtowvl+DnPoqashkYXvGjY6ZFvaXwh9JlMioUCrHPf\nGMEZvlAJZ1pNe8aMX+Vf0gcisHA0l8P49bDu387BdoW9Lu6KqnU4gHtWR/f0QGan\nX27lk8E8/QKBgQDt02yq8u5t212oL01oFAP70svEtIhnm5XPoLOI5MKBaLb0RFE3\nfsWQjiImgtsvo/G+9lfZ1LsR7gcAYmsh35lU2jZ4yyYFxQAIy0YfEheOrQpT4SEK\nXUVaQEkGt/VIfH2zO8aIAHNbH5LNZCaqInMGHMQmtnsHZDa8kgCK2z/WtQKBgGCF\nzdyjjmFD9hPeD7uOP4OeP6Cxd6D9Nfq2+kaOPZNWo7eEl1MTrQPnOhkDFRT8Epuf\nyKxxKzD96qmIMmYnYSOzl8+LM9Yb02hxuJs/ANLgUXiQsSk9EXcifFvzWzBQITd3\nYI8R7maUirkmjIFr0RC5ABPvB30XzdmXUYLIMDq5AoGAdTMrx0JN3CeHMteqMRse\nC7WMjboCKr7Sr+5Z3ZpOfZywuuDtLJ3WSC7n4tMahMK8QAKEZ5IQZrsanW/tXitD\nAL7IzqaAttNXT2ABO1/JDaVcfW8HO1ZbFWDMFzZc5x0BqRuQW1mz6c6a5C85MUhY\nOY05RLpUE4e+sjtAkZhgVig=\n-----END PRIVATE KEY-----\n"
