# Generated by Django 5.2.5 on 2025-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('bloodGroup', models.CharField(db_column='blood_group', max_length=10)),
                ('applyType', models.CharField(choices=[('need', 'Need'), ('donate', 'Donate')], db_column='apply_type', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('lastDonatedAt', models.DateTimeField(blank=True, db_column='last_donated_at', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'blood_donations',
                'indexes': [models.Index(fields=['applyType'], name='blood_donat_apply_t_d9a7ea_idx'), models.Index(fields=['bloodGroup'], name='blood_donat_blood_g_0f0caa_idx'), models.Index(fields=['status'], name='blood_donat_status_d819f8_idx'), models.Index(fields=['createdAt'], name='blood_donat_created_d19dc1_idx')],
            },
        ),
    ]
